#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
# BSPWMRC | Hacker environment                                             
# Enríque González (Aka. Usergh0st)
# Color theme: Xavier
# xprop | grep WM_CLASS

# Bspwm monitors for six.
bspc monitor -d I II III IV V VI

# Cursor mouse fix.
xsetroot -cursor_name left_ptr &

# Bspwm config
bspc config border_width         1
bspc config focused_border_color \#edefec
bspc config normal_border_color \#7d8b94
bspc config window_gap          5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config gapless_monocle true
bspc config paddingless_monocle true

# Bspwm rules.
bspc rule -a 'SimpleScreenRecorder' state=floating follow=on
bspc rule -a 'BleachBit' state=floating follow=on
bspc rule -a 'stacer' state=floating follow=on
bspc rule -a 'org.gnome.Nautilus' state=floating follow=on
bspc rule -a 'gnome-calculator' state=floating follow=on
bspc rule -a 'Nitrogen' state=floating follow=on
bspc rule -a 'Synaptic' state=floating follow=on

# Auto-Start

# Starting sxhkd daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Starting picom compositor.
pgrep -x picom > /dev/null || picom &

# Starting polybar cuts.
${HOME}/.config/polybar/launch.sh --cuts &

# Starting walls scripts.
${HOME}/scripts/wall-scripts/xavier_wal.sh &
